"""Export results to CSV, JSON, TXT, and Markdown."""

from __future__ import annotations

import csv
import json
import re
from datetime import UTC, datetime
from pathlib import Path

from src.config import ensure_exports_dir
from src.models import ExtractedEmail, ExtractionStats, SearchParams
from src.search.query_builder import build_search_query


def _slug(text: str) -> str:
    """Create filesystem-safe slug from text."""
    slug = text.strip().lower().replace(" ", "_")
    return "".join(c if c.isalnum() or c in "-_" else "" for c in slug) or "export"


def build_tags(params: SearchParams) -> str:
    """Slugified subject + location for Inbox Flow tags column."""
    subject = _slug(params.subject)
    location = _slug(params.location) if params.location.strip() else ""
    if location:
        return f"{subject}_{location}"
    return subject


def _capitalize_name(part: str) -> str:
    return part[:1].upper() + part[1:].lower() if part else ""


def names_from_email(email: str) -> tuple[str, str]:
    """Derive firstName / lastName from the email local part."""
    local = email.rsplit("@", 1)[0]
    parts = [p for p in re.split(r"[._\-+]+", local) if p and not p.isdigit()]
    if not parts:
        return "", ""
    if len(parts) == 1:
        return _capitalize_name(parts[0]), ""
    first = _capitalize_name(parts[0])
    last = " ".join(_capitalize_name(p) for p in parts[1:])
    return first, last


def utc_timestamp() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_filename(params: SearchParams, ext: str, prefix: str = "extract") -> str:
    date_str = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    subject = _slug(params.subject)
    location = _slug(params.location) if params.location else "anywhere"
    return f"{prefix}_{subject}_{location}_{date_str}.{ext}"


def _resolve_out_dir(export_dir: Path | None) -> Path:
    return ensure_exports_dir(export_dir)


def export_csv(
    emails: list[ExtractedEmail],
    params: SearchParams,
    stats: ExtractionStats | None = None,
    export_dir: Path | None = None,
) -> Path:
    out_dir = _resolve_out_dir(export_dir)
    path = out_dir / build_filename(params, "csv")
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Email", "Domain", "Source URL", "Context"])
        for e in emails:
            writer.writerow([e.email, e.domain, e.source_url, e.context])
    return path


def export_json(
    emails: list[ExtractedEmail],
    params: SearchParams,
    stats: ExtractionStats | None = None,
    export_dir: Path | None = None,
) -> Path:
    out_dir = _resolve_out_dir(export_dir)
    path = out_dir / build_filename(params, "json")
    data = {
        "exported_at_utc": utc_timestamp(),
        "query": {
            "subject": params.subject,
            "location": params.location,
            "domains": params.domains,
            "max_results": params.max_results,
            "mode": params.mode.value,
            "search_query": build_search_query(
                params.subject, params.location, params.domains
            ),
        },
        "stats": {
            "total_found": stats.total_found if stats else len(emails),
            "unique_count": stats.unique_count if stats else len(emails),
            "duplicates_removed": stats.duplicates_removed if stats else 0,
        },
        "emails": [
            {
                "email": e.email,
                "domain": e.domain,
                "source_url": e.source_url,
                "context": e.context,
            }
            for e in emails
        ],
    }
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return path


def export_txt(
    emails: list[ExtractedEmail],
    params: SearchParams,
    stats: ExtractionStats | None = None,
    export_dir: Path | None = None,
) -> Path:
    out_dir = _resolve_out_dir(export_dir)
    path = out_dir / build_filename(params, "txt")
    lines = [e.email for e in emails]
    path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return path


def export_markdown(
    emails: list[ExtractedEmail],
    params: SearchParams,
    stats: ExtractionStats | None = None,
    export_dir: Path | None = None,
) -> Path:
    out_dir = _resolve_out_dir(export_dir)
    path = out_dir / build_filename(params, "md")
    ts = utc_timestamp()
    search_query = build_search_query(params.subject, params.location, params.domains)
    total = stats.total_found if stats else len(emails)
    unique = stats.unique_count if stats else len(emails)
    dupes = stats.duplicates_removed if stats else 0

    lines = [
        "# LeadMine Extractor Report",
        "",
        "> Public-data email extraction report generated by **LeadMine Extractor**.",
        "",
        "## Query Metadata",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| **Subject / role** | {params.subject} |",
        f"| **Location** | {params.location or 'N/A'} |",
        f"| **Domains** | {', '.join(params.domains)} |",
        f"| **Max results** | {params.max_results} |",
        f"| **Mode** | {params.mode.value} |",
        f"| **Search query** | `{search_query}` |",
        "",
        f"**Exported (UTC):** `{ts}`",
        "",
        "## Summary",
        "",
        f"- **Total found:** {total}",
        f"- **Unique emails:** {unique}",
        f"- **Duplicates removed:** {dupes}",
        "",
        "## Results",
        "",
        "| Email | Domain | Source URL | Context |",
        "| --- | --- | --- | --- |",
    ]
    for e in emails:
        ctx = e.context.replace("|", "\\|")
        src = e.source_url.replace("|", "\\|")
        lines.append(f"| `{e.email}` | `{e.domain}` | {src} | {ctx} |")

    lines.extend(
        [
            "",
            "---",
            "",
            "*Compliance: public data only. User responsible for CAN-SPAM/GDPR.*",
            "",
        ]
    )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def export_inbox_flow_csv(
    emails: list[ExtractedEmail],
    params: SearchParams,
    stats: ExtractionStats | None = None,
    export_dir: Path | None = None,
) -> Path:
    """Inbox Flow contacts CSV: email, firstName, lastName, source, tags."""
    out_dir = _resolve_out_dir(export_dir)
    path = out_dir / build_filename(params, "csv", prefix="inbox_flow_contacts")
    tags = build_tags(params)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["email", "firstName", "lastName", "source", "tags"])
        for e in emails:
            first, last = names_from_email(e.email)
            writer.writerow([e.email, first, last, e.source_url, tags])
    return path


EXPORTERS = {
    "csv": export_csv,
    "json": export_json,
    "txt": export_txt,
    "md": export_markdown,
    "inbox_flow": export_inbox_flow_csv,
}
