import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  buildSearchQuery,
  buildTags,
  namesFromEmail,
  slug,
  type ExtractedEmail,
  type ExtractionStats,
  type SearchParams,
} from './extract.js';

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
  return dir;
}

function filename(params: SearchParams, ext: string, prefix = 'extract') {
  const date = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
  const subject = slug(params.subject);
  const location = params.location.trim() ? slug(params.location) : 'anywhere';
  return `${prefix}_${subject}_${location}_${date}.${ext}`;
}

export function exportCsv(
  emails: ExtractedEmail[],
  params: SearchParams,
  exportDir: string,
): string {
  const dir = ensureDir(exportDir);
  const file = path.join(dir, filename(params, 'csv'));
  const rows = [
    'Email,Domain,Source URL,Context',
    ...emails.map(
      (e) =>
        `"${e.email}","${e.domain}","${e.sourceUrl.replace(/"/g, '""')}","${e.context.replace(/"/g, '""')}"`,
    ),
  ];
  writeFileSync(file, rows.join('\n') + '\n', 'utf8');
  return file;
}

export function exportJson(
  emails: ExtractedEmail[],
  params: SearchParams,
  stats: ExtractionStats,
  exportDir: string,
): string {
  const dir = ensureDir(exportDir);
  const file = path.join(dir, filename(params, 'json'));
  writeFileSync(
    file,
    JSON.stringify(
      {
        exportedAtUtc: new Date().toISOString(),
        query: {
          subject: params.subject,
          location: params.location,
          domains: params.domains,
          maxResults: params.maxResults,
          mode: params.mode,
          searchQuery: buildSearchQuery(params.subject, params.location, params.domains),
        },
        stats,
        emails,
      },
      null,
      2,
    ),
    'utf8',
  );
  return file;
}

export function exportTxt(
  emails: ExtractedEmail[],
  params: SearchParams,
  exportDir: string,
): string {
  const dir = ensureDir(exportDir);
  const file = path.join(dir, filename(params, 'txt'));
  writeFileSync(file, emails.map((e) => e.email).join('\n') + (emails.length ? '\n' : ''), 'utf8');
  return file;
}

export function exportMarkdown(
  emails: ExtractedEmail[],
  params: SearchParams,
  stats: ExtractionStats,
  exportDir: string,
): string {
  const dir = ensureDir(exportDir);
  const file = path.join(dir, filename(params, 'md'));
  const ts = new Date().toISOString();
  const q = buildSearchQuery(params.subject, params.location, params.domains);
  const lines = [
    '# LeadMine Extractor Report',
    '',
    '> Public-data email extraction report generated by **LeadMine Extractor**.',
    '',
    '## Query Metadata',
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| **Subject / role** | ${params.subject} |`,
    `| **Location** | ${params.location || 'N/A'} |`,
    `| **Domains** | ${params.domains.join(', ')} |`,
    `| **Max results** | ${params.maxResults} |`,
    `| **Mode** | ${params.mode} |`,
    `| **Search query** | \`${q}\` |`,
    '',
    `**Exported (UTC):** \`${ts}\``,
    '',
    '## Summary',
    '',
    `- **Total found:** ${stats.totalFound}`,
    `- **Unique emails:** ${stats.uniqueCount}`,
    `- **Duplicates removed:** ${stats.duplicatesRemoved}`,
    '',
    '## Results',
    '',
    '| Email | Domain | Source URL | Context |',
    '| --- | --- | --- | --- |',
    ...emails.map(
      (e) =>
        `| \`${e.email}\` | \`${e.domain}\` | ${e.sourceUrl.replace(/\|/g, '\\|')} | ${e.context.replace(/\|/g, '\\|')} |`,
    ),
    '',
    '---',
    '',
    '*Compliance: public data only. User responsible for CAN-SPAM/GDPR.*',
    '',
  ];
  writeFileSync(file, lines.join('\n'), 'utf8');
  return file;
}

export function exportInboxFlowCsv(
  emails: ExtractedEmail[],
  params: SearchParams,
  exportDir: string,
): string {
  const dir = ensureDir(exportDir);
  const file = path.join(dir, filename(params, 'csv', 'inbox_flow_contacts'));
  const tags = buildTags(params.subject, params.location);
  const rows = [
    'email,firstName,lastName,source,tags',
    ...emails.map((e) => {
      const { firstName, lastName } = namesFromEmail(e.email);
      return `"${e.email}","${firstName}","${lastName}","${e.sourceUrl.replace(/"/g, '""')}","${tags}"`;
    }),
  ];
  writeFileSync(file, rows.join('\n') + '\n', 'utf8');
  return file;
}
